language: node_js
node_js:
- "node"
- "lts/*"
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn build --prefix-paths
- yarn lint
deploy:
  provider: pages
  allow_failure: true
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master
